# Generated by Django 5.2.17 on 2026-09-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_suluh_djiwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
